name: MythicCore
version: '${project.version}'
main: com.dev.mythiccore.MythicCore
api-version: 1.19
depend: [MMOCore, MMOItems, MythicLib, MythicMob]
softdepend: [PlaceholderAPI, HolographicDisplays]
authors: [downYoutube2548, Teenkung123]
commands:
  mythiccore:
    permission: mythiccore.admin
